export let buttons = [
    {
        id: 1,
        link: "/admin/roles",
        imageDark: "./imageButton/rolesDark.svg",
        imageLight: "./imageButton/rolesLight.svg",
        textEN: "Roles",
        textRU: "Роли",
    },
    {
        id: 2,
        link: "/admin/landing",
        imageDark: "./imageButton/landingDark.svg",
        imageLight: "./imageButton/landingLight.svg",
        textEN: "Landing",
        textRU: "Landing",
    },
    {
        id: 3,
        link: "/admin/groups",
        imageDark: "./imageButton/groupsDark.svg",
        imageLight: "./imageButton/groupsLight.svg",
        textEN: "Groups",
        textRU: "Группы",
    },
    {
        id: 4,
        link: "/admin/news",
        imageDark: "./imageButton/newsDark.svg",
        imageLight: "./imageButton/newsLight.svg",
        textEN: "Newc",
        textRU: "Новости",
    },
    {
        id: 5,
        link: "/admin/calendar",
        imageDark: "./imageButton/calendarDark.svg",
        imageLight: "./imageButton/calendarLight.svg",
        textEN: "Calendar",
        textRU: "Календарь",
    },
    {
        id: 6,
        link: "/admin/statistics",
        imageDark: "./imageButton/statisticsDark.svg",
        imageLight: "./imageButton/statisticsLight.svg",
        textEN: "Statistics",
        textRU: "Статистика",
    },
]